### ISSUE TITLE
Error while downloading the data

### ISSUE THREAD

**Issue by R1j1t** [Auquan/qq-optiver#2]
I download the Problem 3 folder and executed `problem3_template.py` and I am getting the following error:

```bash

Processing data for stock: EXR
Processing data for stock: BYB
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtester/timeRule/nse_time_rule.py", line 31, in getNSEHolidays
    soup = BeautifulSoup(content, 'lxml')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "problem3_template.py", line 176, in <module>
    tradingSystem = TradingSystem(tsParams)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtester/trading_system.py", line 49, in __init__
    self.tsParams.getTimeRuleForUpdates(), self.initializer)
  File "/Users/rajat/Desktop/placementTests/qq-optiver/problem3/problem3_trading_params.py", line 62, in getTimeRuleForUpdates
    return NSETimeRule(startDate=self.__startDate, endDate=self.__endDate, startTime='15:30', frequency='M', sample='1440')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtester/timeRule/nse_time_rule.py", line 15, in __init__
    super(NSETimeRule, self).__init__(startDate = startDate, endDate = endDate, startTime = startTime, endTime= endTime, holidays = self.getNSEHolidays(), frequency = frequency, sample = sample)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/backtester/timeRule/nse_time_rule.py", line 37, in getNSEHolidays
    except HTTPError as e:
NameError: name 'HTTPError' is not defined

```

Can you please point out the problem.

Python 3.5.4
OS: Mac OS High Sierra

**Comment by R1j1t** [comment]
Solved the issue.

For this exception 
`Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`
use 
`pip3 install lxml`

and for `name 'HTTPError' is not defined`

update the nse_time_rule.py file with `HTTPError` import. I have also created a pull request on bitbucket. Closing this issue.
